/**
 * Task Threads Types
 * P6.6: Human Interaction Layer, Task Threads & Conversational Control
 *
 * Types for conversational task management with threads, messages, and context.
 */

import type { TaskOutput, TaskArtifact } from '../task-results/types'

/**
 * Human-readable task states (beyond just pending/running/completed)
 * P6.7: Added planning, reusing_strategy, validating, waiting_input, needs_artifacts, needs_outputs
 */
export type HumanTaskState =
  | 'thinking'              // AI is analyzing/planning
  | 'planning'              // P6.7: Building execution plan
  | 'reusing_strategy'      // P6.7: Pattern found, reusing strategy
  | 'queued'                // Waiting in queue
  | 'executing'             // Running steps
  | 'validating'            // P6.7: Verifying results
  | 'waiting_approval'      // Needs user approval to continue
  | 'waiting_user_input'    // Needs additional info from user
  | 'waiting_input'         // P6.7: Alias for waiting_user_input
  | 'paused'                // User paused the task
  | 'completed'             // Successfully completed
  | 'failed'                // Failed with error
  | 'needs_repair'          // Requires repair/troubleshooting
  | 'needs_artifacts'       // P6.7: Missing artifacts for validation
  | 'needs_outputs'         // P6.7: Missing outputs for validation
  | 'cancelled'             // User cancelled

/**
 * Thread message role
 */
export type MessageRole =
  | 'user'          // User message
  | 'assistant'     // GranClaw response
  | 'system'        // System notification
  | 'runtime'       // Runtime event (step completed, error, etc.)

/**
 * Task action type for messages
 */
export type ThreadTaskAction =
  | 'continue'      // "continúa"
  | 'pause'         // "pausa"
  | 'resume'        // "reanuda"
  | 'refine'        // Change parameters
  | 'approve'       // Approve pending action
  | 'reject'        // Reject pending action
  | 'retry'         // Retry failed action
  | 'cancel'        // Cancel task
  | 'explain'       // Request explanation
  | 'show_artifact' // Show specific artifact

/**
 * A single message within a thread
 */
export interface ThreadMessage {
  id: string
  role: MessageRole
  content: string
  timestamp: string
  // Optional task-related metadata
  taskAction?: ThreadTaskAction
  workflowStep?: {
    stepId: string
    stepName: string
    status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped'
  }
  // Optional outputs/artifacts generated by this message
  artifacts?: TaskArtifact[]
  outputs?: TaskOutput[]
  // For approval requests
  pendingApproval?: {
    id: string
    action: string
    description: string
    risks?: string[]
    options?: string[]
  }
  // For explanations
  explanation?: {
    what: string
    why: string
    nextSteps: string[]
  }
}

/**
 * Thread context - preferences and memory within the thread
 */
export interface ThreadContext {
  // User preferences for this thread
  preferences: Record<string, string | number | boolean>
  // Filters applied (e.g., "solo gratuito")
  filters: string[]
  // Decisions made
  decisions: Array<{
    key: string
    value: string
    reason: string
    timestamp: string
  }>
  // Entities mentioned
  entities: Array<{
    type: string
    name: string
    firstMentioned: string
  }>
}

/**
 * Execution plan shown to user before executing
 */
export interface HumanReadablePlan {
  summary: string
  steps: Array<{
    order: number
    description: string
    requiresApproval: boolean
    estimatedDuration?: string
    risks?: string[]
  }>
  totalSteps: number
  estimatedDuration?: string
  permissions?: string[]
  warnings?: string[]
}

/**
 * Pending approval within a thread
 */
export interface PendingApproval {
  id: string
  type: 'execute' | 'install' | 'download' | 'modify' | 'delete' | 'other'
  action: string
  description: string
  risks: string[]
  createdAt: string
  expiresAt?: string
  status: 'pending' | 'approved' | 'rejected' | 'expired'
  resolvedAt?: string
  resolvedBy?: string
}

/**
 * A task thread - the conversational wrapper around a task
 */
export interface TaskThread {
  id: string
  // Links to task/workflow
  taskId?: string
  workflowId?: string
  compositeTaskId?: string
  // Owner
  tenantId: string
  userId?: string
  // Thread metadata
  title: string
  status: HumanTaskState
  // Messages
  messages: ThreadMessage[]
  // Context and memory
  activeContext: ThreadContext
  // Current plan (if any)
  currentPlan?: HumanReadablePlan
  // Last understood user intent
  lastUserIntent?: string
  // Pending approvals
  pendingApprovals: PendingApproval[]
  // Timestamps
  createdAt: string
  updatedAt: string
  lastActivityAt: string
}

/**
 * Input for creating a thread
 */
export interface CreateThreadInput {
  tenantId: string
  userId?: string
  taskId?: string
  workflowId?: string
  title: string
  initialMessage?: string
}

/**
 * Input for adding a message to a thread
 */
export interface AddMessageInput {
  threadId: string
  role: MessageRole
  content: string
  taskAction?: ThreadTaskAction
  workflowStep?: ThreadMessage['workflowStep']
  artifacts?: TaskArtifact[]
  outputs?: TaskOutput[]
  pendingApproval?: ThreadMessage['pendingApproval']
  explanation?: ThreadMessage['explanation']
}

/**
 * Input for updating thread context
 */
export interface UpdateContextInput {
  threadId: string
  preferences?: Record<string, string | number | boolean>
  filters?: string[]
  decision?: {
    key: string
    value: string
    reason: string
  }
  entity?: {
    type: string
    name: string
  }
}

/**
 * Input for refinement
 */
export interface RefinementInput {
  threadId: string
  refinement: string
  applyTo?: 'plan' | 'current_step' | 'all'
}

/**
 * Thread state for persistence
 */
export interface TaskThreadState {
  version: number
  threads: TaskThread[]
  lastUpdated: string
  stats: {
    totalThreads: number
    activeThreads: number
    completedThreads: number
  }
}

/**
 * Default thread state
 */
export const DEFAULT_THREAD_STATE: TaskThreadState = {
  version: 1,
  threads: [],
  lastUpdated: new Date().toISOString(),
  stats: {
    totalThreads: 0,
    activeThreads: 0,
    completedThreads: 0
  }
}

/**
 * Default thread context
 */
export const DEFAULT_THREAD_CONTEXT: ThreadContext = {
  preferences: {},
  filters: [],
  decisions: [],
  entities: []
}
