#!/bin/zsh
#
# setup-env.sh - Generate .env with real OpenClaw token
# FIX 042: Deploy reproducible without manual TUI steps
#
# Usage:
#   ./scripts/setup-env.sh
#
# This script reads the gateway token from openclaw config
# and generates a valid .env file with the real token value.
#
# IMPORTANT:
# - Do NOT use command substitution in .env (e.g., $(openclaw config get ...))
# - The token must be the actual value, not a command
#

set -euo pipefail

# Detect script root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT"

echo "[ENV] Generating .env from OpenClaw config..."

# Get real token value (not command substitution string)
TOKEN=$(openclaw config get gateway.token 2>/dev/null || true)

if [[ -z "$TOKEN" ]]; then
  echo "[ENV] ERROR: Could not get gateway token from openclaw config"
  echo "[ENV] Make sure OpenClaw is installed and configured"
  echo "[ENV] Try: openclaw config get gateway.token"
  exit 1
fi

# Generate .env with real values
cat > .env <<EOF
# Generated by setup-env.sh - FIX 042
# Do NOT edit manually unless you know what you're doing

# Application Ports
APP_PORT=3001
WEB_PORT=5173
NODE_ENV=development

# OpenClaw Connection
OPENCLAW_BASE_URL=http://localhost:18789
OPENCLAW_WS_URL=ws://localhost:18789/__openclaw__/ws
OPENCLAW_API_KEY=$TOKEN

# WebSocket Client Identity (FIX 034)
OPENCLAW_WS_CLIENT_ID=gateway-client
OPENCLAW_WS_CLIENT_MODE=backend

# Web UI
VITE_API_URL=http://localhost:3001
EOF

echo "[ENV] OK - .env generated with real token"
echo "[ENV] Token prefix: ${TOKEN:0:8}..."
